Works/DjangoBasic/about/urls.py
from django.urls import path
from .views import about

app_name = 'about'

urlpatterns = [
    path('', about, name='about')
]

Works/DjangoBasic/blog/urls.py
from django.urls import path
from .views import blog,blog_details

app_name = 'blog'

urlpatterns = [
    path('', blog,name='blog'),
    path('blog-detail/<slug:slug>/', blog_details, name='blog-detail'),
]

Works/DjangoBasic/contact/urls.py
from django.urls import path
from .views import contact

app_name = 'contact'

urlpatterns=[
    path('',contact,name='contact')
]

Works/DjangoBasic/core/urls.py
from django.contrib import admin
from django.urls import path,include
# from blog.views import blog
# from about.views import about
# from blog.admin import blog

from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/',admin.site.urls),
    # path('blogadmin/', blog.urls),
    path('',include('blog.urls', namespace='blog')),
    path('about/',include('about.urls',namespace='about')),
    path('contact/',include('contact.urls',namespace='contact'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


# admin.site.index_title = 'Admin Panel (by: yusifiz)'
# admin.site.site_header = 'Admin'
# admin.site.site_title = 'Django'

Works/DjangoBasic/about/models.py
from django.db import models

# Create your models here.


class About(models.Model):
    title = models.CharField(max_length=127, null=True, blank=True)
    text = models.TextField(help_text='Main info..')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

Works/DjangoBasic/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text  import slugify
import string,random
from django.db.models.signals import pre_save
from core.utils import  unique_slug_generator
# Create your models here.


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))
    
class Blog(models.Model):
    title = models.CharField(max_length=127, null=True, blank=True)
    text = models.TextField(help_text='Main info..')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=63, verbose_name='Muellif',null=True,blank=True)
    slug = models.SlugField(max_length=255, null=True,unique=True,blank=True)
    image = models.ImageField(upload_to="blog/", null=True)



    def get_absolute_url(self):
        return reverse('blog:blog-detail', args=[self.slug])
    
    
    
    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'
        ordering = ('created_at',)

    def __str__(self):
        return self.title
    

def slug_generator(sender, instance, *args, **kwargs):
        if not instance.slug:
            instance.slug = unique_slug_generator(instance)
            
pre_save.connect(slug_generator, sender=Blog)

Works/DjangoBasic/contact/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    fullname = models.CharField(max_length=100,blank=True,null=True)
    email = models.CharField(max_length=100,blank=True,null=True)
    message = models.TextField()
    subject = models.CharField(max_length=100,)
    
    def __str__(self):
        return self.fullname

Works/DjangoBasic/product/models.py
from django.db import models

class Product(models.Model):
    COLORS = (
        (1, 'black'),
        (2, 'white'),
        (3, 'red')
    )
    name = models.CharField(max_length=200, help_text='Enter product name')
    color = models.IntegerField(choices=COLORS,)
    price = models.IntegerField(default=1)
    product_tag = models.ManyToManyField('Tag')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    title = models.CharField(max_length=63, null=True, blank=True)

    def __str__(self):
        return self.title

Works/DjangoBasic/contact/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from contact.utils.validators import mail_validator
from .models import Contact

class ContactForm(forms.ModelForm):
    email = forms.EmailField(label='Email',max_length=100,validators=(mail_validator,) ,widget=forms.EmailInput(
        attrs = {'class': 'form-control d-flex flex-column ','placeholder': ' Your Email..'}
    ))
    
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
            'fullname': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Your Name...'}),

            'subject': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Subject...'}),
            'message': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': 'Your Message...'})
        }

Works/DjangoBasic/about/views.py
from django.shortcuts import render

from about.models import About

# Create your views here.

def about(request):
    abouts = About.objects.all()
    return render(request,'about.html',{'abouts':abouts})

Works/DjangoBasic/blog/views.py
from django.shortcuts import render
from .models import Blog
from django.shortcuts import get_object_or_404
# Create your views here.
def blog(request):
    blogs = Blog.objects.all()

    return render(request,'blog.html',{'blogs' : blogs})

def blog_details(request,slug):
    
    blogs = get_object_or_404(Blog, slug=slug)
    return render(request, "blog-details.html",{'blogs' : blogs})

Works/DjangoBasic/contact/views.py
from django import forms
from django.shortcuts import redirect, render
from . forms import ContactForm
from contact.utils.validators import ValidationError
from django.contrib import messages


def contact(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Successfuly registration!')
            return redirect('/contact')
        else:
            messages.add_message(request, messages.INFO, 'Your mail is not valid!')
        
    return render(request, 'contact.html', {'form': form})

Works/DjangoBasic/templates/about.html
{% extends "base.html" %} 

{% load static %}

{% block css %} 

<link rel="stylesheet" href="{% static 'css/about.css' %}">

{% endblock %}

{% block content %} 


{% filter force_escape|lower %}
About'un esas kontenti
{% endfilter %}

{% for about in abouts %}


<div class="card m-5" style="width: 18rem;">
  <!-- <img src="..." class="card-img-top" alt="..."> -->
  <div class="card-body">
    <h5 class="card-title">{{about.title}}</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
{% endfor %}
{% endblock %}

Works/DjangoBasic/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <title>Django</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block css %} {% endblock %}
  </head>
  <body>
    
      {% include 'includes/navbar.html' %}
      
      {% block content %}   {% endblock %}

      {% include 'includes/footer.html' %}
      
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

Works/DjangoBasic/templates/blog-details.html
{% extends "base.html" %}

{% block content %}
<h1>{{blogs.title}}</h1>
{% endblock %}

Works/DjangoBasic/templates/blog.html
{% extends "base.html" %} 
{% load static custom_filter custom_tag %}

{% block css %} 

<link rel="stylesheet" href="{% static 'css/blog.css' %}">

{% endblock %}

{% block content %} 
<h1 class="m-5">Blogun esas kontenti</h1>
{% for blog in blogs %}

<h3>Blog - {{ forloop.counter }}</h3>

<div class="card m-5" style="width: 18rem;">
  <img src="{{ blog.image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ blog.title|my_uppercase }}</h5>
    <p class="card-text text-warning">{{ blog.text|truncatechars:4 }}</p>
    <p class="card-text text-warning">Created : {{ blog.created_at|date:"M Y" }}</p>
    {% current_time "%Y-%m-%d %I:%M %p" as the_time %}
    <p class="text-danger">My custom tag for date : {{ the_time }}.</p>
    <a href="{{ blog.get_absolute_url }}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
{% empty %}
<h1>Blog is not available</h1>
{% endfor %}

{% endblock %}

Works/DjangoBasic/templates/contact.html
{% extends "base.html" %}
{% block content %}

<h1>Contact</h1>

    <form class="form-inline d-flex flex-column justify-content-center align-items-center m-5" method="post">
        {% csrf_token %}

        {% for field in form %}
      
            <div class="form-group ">
                {{ field.label_tag }}
                {{ field}}
            </div>
        {% endfor %}
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <input class="m-5" type="submit" value="Submit">
    </form>
{% endblock %}

Works/DjangoBasic/templates/includes/footer.html
<footer class="bg-light text-center text-lg-start">
    <!-- Grid container -->
    <div class="container p-4">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>
  
          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-dark">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-0">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!" class="text-dark">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>
  
          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-dark">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-0">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!" class="text-dark">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-dark">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    {% comment "test" %}
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    {% endcomment %}
    <!-- Copyright -->
  </footer>

Works/DjangoBasic/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:blog' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
          </li>
          
        </ul>
      </div>
    </div>
</nav>